# Generated by Django 6.0.1 on 2026-01-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryUserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_status', models.CharField(choices=[('active', 'active'), ('moderation', 'moderation'), ('denied', 'denied')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
